script: bash -ex .travis-ci.sh
env: 
  global: 
  - secure: Ycg8VpDVCCXgO5QOqUywTAiycLhrXilTYjYjK2sLgwJtLvW3EPDHV/j89AlrhZ3N10OXn3KVObiOPjk7mDgcNqtnTVnA0qJ0Ai43F/zFop+hAWR3WKAuudLENA4lmp3bW+9Z/+DDpNNOY2TrwRIYeBeYAvvvSsJes4IG0Wwje0o=
  matrix: 
  - OCAML_VERSION=4.01.0 OPAM_VERSION=1.1.0
language: c
branches:
  only:
  - master